project_id = "qczmdbqwpshioooncpjd"

[functions.facebook-webhook]
verify_jwt = false

[functions.facebook-oauth]
verify_jwt = false

[functions.ai-agent-chat]
verify_jwt = false

[functions.evolution-api]
verify_jwt = false

[functions.check-no-response]
verify_jwt = false

[functions.weekly-report]
verify_jwt = false

[functions.meta-send-message]
verify_jwt = false

[functions.send-scheduled-messages]
verify_jwt = false

[functions.invite-member]
verify_jwt = false

[functions.accept-invite]
verify_jwt = false

[functions.set-user-password]
verify_jwt = false

[functions.create-workspace]
verify_jwt = false
